// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// skewnessRcpp
double skewnessRcpp(NumericVector x);
RcppExport SEXP kongRa_skewnessRcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(skewnessRcpp(x));
    return rcpp_result_gen;
END_RCPP
}
// armaTest
double armaTest();
RcppExport SEXP kongRa_armaTest() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(armaTest());
    return rcpp_result_gen;
END_RCPP
}
