# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
boolsAndInterveawe <- function(b, other) {
    .Call('_koR_boolsAndInterveawe', PACKAGE = 'koR', b, other)
}

#' Works like System.arraycopy(...) in Java for integer vectors.
#' @export
copyInts <- function(src, srcPos, dest, destPos, length) {
    invisible(.Call('_koR_copyInts', PACKAGE = 'koR', src, srcPos, dest, destPos, length))
}

#' Works like System.arraycopy(...) in Java for double vectors.
#' @export
copyDoubles <- function(src, srcPos, dest, destPos, length) {
    invisible(.Call('_koR_copyDoubles', PACKAGE = 'koR', src, srcPos, dest, destPos, length))
}

#' Computes number of work days (1-5/Mon-Fri) fot the total number of days and
#' starting with the initial day of week (1-7/Mon-Sun).
#' @export
countWorkdays <- function(dayOfWeek, daysCount) {
    .Call('_koR_countWorkdays', PACKAGE = 'koR', dayOfWeek, daysCount)
}

