# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns the skewness of the vector. No NAs assumed.
#'
#' @param x the vector
#' @export
skewnessRcpp <- function(x) {
    .Call('kongRa_skewnessRcpp', PACKAGE = 'kongRa', x)
}

